// Generated by tooling/scripts/generate-tokens.mjs. Do not edit directly.
export const theme = {
  "source": {
    "primary": "#4F46E5"
  },
  "colors": {
    "background": "#FFFBFF",
    "foreground": "#1C1B1F",
    "primary": "#4D44E3",
    "secondary": "#5E5C71",
    "tertiary": "#7A5368",
    "error": "#BA1A1A",
    "danger": "#BA1A1A"
  },
  "schemes": {
    "light": {
      "primary": "#4D44E3",
      "onPrimary": "#FFFFFF",
      "primaryContainer": "#E2DFFF",
      "onPrimaryContainer": "#0F0069",
      "secondary": "#5E5C71",
      "onSecondary": "#FFFFFF",
      "secondaryContainer": "#E3E0F9",
      "onSecondaryContainer": "#1A1A2C",
      "tertiary": "#7A5368",
      "onTertiary": "#FFFFFF",
      "tertiaryContainer": "#FFD8EA",
      "onTertiaryContainer": "#2F1123",
      "error": "#BA1A1A",
      "onError": "#FFFFFF",
      "errorContainer": "#FFDAD6",
      "onErrorContainer": "#410002",
      "background": "#FFFBFF",
      "onBackground": "#1C1B1F",
      "surface": "#FFFBFF",
      "onSurface": "#1C1B1F",
      "surfaceVariant": "#E4E1EC",
      "onSurfaceVariant": "#47464F",
      "outline": "#787680",
      "outlineVariant": "#C8C5D0",
      "shadow": "#000000",
      "scrim": "#000000",
      "inverseSurface": "#313034",
      "inverseOnSurface": "#F3EFF4",
      "inversePrimary": "#C3C0FF"
    },
    "dark": {
      "primary": "#C3C0FF",
      "onPrimary": "#1D00A5",
      "primaryContainer": "#3323CC",
      "onPrimaryContainer": "#E2DFFF",
      "secondary": "#C7C4DD",
      "onSecondary": "#2F2E42",
      "secondaryContainer": "#464559",
      "onSecondaryContainer": "#E3E0F9",
      "tertiary": "#EAB9D1",
      "onTertiary": "#472639",
      "tertiaryContainer": "#603C50",
      "onTertiaryContainer": "#FFD8EA",
      "error": "#FFB4AB",
      "onError": "#690005",
      "errorContainer": "#93000A",
      "onErrorContainer": "#FFB4AB",
      "background": "#1C1B1F",
      "onBackground": "#E5E1E6",
      "surface": "#1C1B1F",
      "onSurface": "#E5E1E6",
      "surfaceVariant": "#47464F",
      "onSurfaceVariant": "#C8C5D0",
      "outline": "#928F9A",
      "outlineVariant": "#47464F",
      "shadow": "#000000",
      "scrim": "#000000",
      "inverseSurface": "#E5E1E6",
      "inverseOnSurface": "#313034",
      "inversePrimary": "#4D44E3"
    }
  },
  "fonts": {
    "body": "Inter_400Regular",
    "heading": "Inter_700Bold"
  },
  "spacing": {
    "xs": 4,
    "sm": 8,
    "md": 16,
    "lg": 24,
    "xl": 32
  },
  "radius": {
    "sm": 6,
    "md": 10,
    "lg": 16,
    "full": 9999
  }
} as const;
export type Theme = typeof theme;
