#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { ROOT, readJson } from "./lib/workspace.mjs";

const tokenRoot = join(ROOT, "packages/design-tokens");
const tokens = await readJson(join(tokenRoot, "tokens.json"));
const header = "// Generated by tooling/scripts/generate-tokens.mjs. Do not edit directly.\n";
const outputs = new Map([
  [join(tokenRoot, "src/index.ts"), `${header}export const theme = ${JSON.stringify(tokens, null, 2)} as const;\nexport type Theme = typeof theme;\n`],
  [join(tokenRoot, "generated/tailwind.cjs"), `${header}module.exports = ${JSON.stringify({ colors: tokens.colors, fontFamily: Object.fromEntries(Object.entries(tokens.fonts).map(([key, value]) => [key, [value]])), spacing: tokens.spacing, borderRadius: tokens.radius }, null, 2)};\n`],
  [join(tokenRoot, "generated/theme.css"), `/* Generated by tooling/scripts/generate-tokens.mjs. Do not edit directly. */\n:root {\n${[
    ...Object.entries(tokens.colors).map(([key, value]) => `  --color-${key}: ${value};`),
    ...Object.entries(tokens.fonts).map(([key, value]) => `  --font-${key}: ${value};`),
    ...Object.entries(tokens.spacing).map(([key, value]) => `  --spacing-${key}: ${value}px;`),
    ...Object.entries(tokens.radius).map(([key, value]) => `  --radius-${key}: ${value}px;`),
  ].join("\n")}\n}\n`],
]);

const check = process.argv.includes("--check");
const stale = [];
for (const [path, expected] of outputs) {
  if (check) {
    const actual = await readFile(path, "utf8").catch(() => "");
    if (actual !== expected) stale.push(path.slice(ROOT.length + 1));
  } else await writeFile(path, expected);
}

if (stale.length) {
  console.error(`Generated design tokens are stale:\n${stale.map((path) => `- ${path}`).join("\n")}\nRun: pnpm tokens:generate`);
  process.exitCode = 1;
} else console.log(check ? "Design tokens are up to date" : `Generated ${outputs.size} design-token outputs`);
