import { parseMobileEnv } from "@monoplate/config/mobile";
export const env = parseMobileEnv({
  EXPO_PUBLIC_API_URL: process.env.EXPO_PUBLIC_API_URL,
  EXPO_PUBLIC_APP_ENV: process.env.EXPO_PUBLIC_APP_ENV,
  EXPO_PUBLIC_SENTRY_DSN: process.env.EXPO_PUBLIC_SENTRY_DSN,
  EXPO_PUBLIC_DEV_HOST: process.env.EXPO_PUBLIC_DEV_HOST,
  EXPO_PUBLIC_MINIMUM_APP_VERSION: process.env.EXPO_PUBLIC_MINIMUM_APP_VERSION,
  EXPO_PUBLIC_RECOMMENDED_APP_VERSION: process.env.EXPO_PUBLIC_RECOMMENDED_APP_VERSION,
  EXPO_PUBLIC_APP_STORE_URL: process.env.EXPO_PUBLIC_APP_STORE_URL,
});
