import { argbFromHex, Hct, hexFromArgb, MaterialDynamicColors, SchemeMonochrome, themeFromSourceColor } from "@material/material-color-utilities";

const hexColorPattern = /^#[0-9a-f]{6}$/i;
const legacyColorKeys = ["background", "foreground", "primary", "danger"];

export function normalizeHexColor(value) {
  const normalized = value.trim().toUpperCase();
  if (!hexColorPattern.test(normalized)) throw new Error("Primary color must use the #RRGGBB format.");
  return normalized;
}

function schemeToHex(scheme) {
  return Object.fromEntries(Object.entries(scheme.toJSON()).map(([name, value]) => [name, hexFromArgb(value).toUpperCase()]));
}

function isAchromatic(hex) {
  return hex.slice(1, 3) === hex.slice(3, 5) && hex.slice(3, 5) === hex.slice(5, 7);
}

function contrastingText(hex) {
  const channels = [1, 3, 5].map((offset) => Number.parseInt(hex.slice(offset, offset + 2), 16) / 255);
  const [red, green, blue] = channels.map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4);
  const luminance = 0.2126 * red + 0.7152 * green + 0.0722 * blue;
  return (luminance + 0.05) / 0.05 >= 4.5 ? "#000000" : "#FFFFFF";
}

function monochromeSchemeToHex(seed, isDark) {
  const scheme = new SchemeMonochrome(Hct.fromInt(argbFromHex(seed)), isDark, 0);
  const colorNames = Object.keys(themeFromSourceColor(argbFromHex(seed)).schemes.light.toJSON());
  const colors = Object.fromEntries(colorNames.map((name) => [name, hexFromArgb(MaterialDynamicColors[name].getArgb(scheme)).toUpperCase()]));
  if (!isDark) {
    colors.primary = seed;
    colors.onPrimary = contrastingText(seed);
  }
  return colors;
}

function schemesFromSeed(seed) {
  if (isAchromatic(seed)) {
    return {
      light: monochromeSchemeToHex(seed, false),
      dark: monochromeSchemeToHex(seed, true),
    };
  }
  const generated = themeFromSourceColor(argbFromHex(seed));
  return { light: schemeToHex(generated.schemes.light), dark: schemeToHex(generated.schemes.dark) };
}

export function buildDesignTokens(source) {
  const primary = normalizeHexColor(source.primary);
  const { light, dark } = schemesFromSeed(primary);
  const roleSeeds = { secondary: source.secondary, tertiary: source.tertiary, error: source.error };
  for (const [role, seed] of Object.entries(roleSeeds)) {
    if (!seed) continue;
    const roleSchemes = schemesFromSeed(normalizeHexColor(seed));
    const roleScheme = roleSchemes.light;
    const roleDarkScheme = roleSchemes.dark;
    const prefix = role === "error" ? "error" : role;
    const sourcePrefix = "primary";
    for (const [target, sourceKey] of [[prefix, sourcePrefix], [`on${prefix[0].toUpperCase()}${prefix.slice(1)}`, `on${sourcePrefix[0].toUpperCase()}${sourcePrefix.slice(1)}`], [`${prefix}Container`, `${sourcePrefix}Container`], [`on${prefix[0].toUpperCase()}${prefix.slice(1)}Container`, `on${sourcePrefix[0].toUpperCase()}${sourcePrefix.slice(1)}Container`]]) {
      light[target] = roleScheme[sourceKey];
      dark[target] = roleDarkScheme[sourceKey];
    }
  }
  return {
    source: { primary, ...(source.secondary ? { secondary: normalizeHexColor(source.secondary) } : {}), ...(source.tertiary ? { tertiary: normalizeHexColor(source.tertiary) } : {}), ...(source.error ? { error: normalizeHexColor(source.error) } : {}) },
    colors: { background: light.background, foreground: light.onBackground, primary: light.primary, secondary: light.secondary, tertiary: light.tertiary, error: light.error, danger: light.error },
    schemes: { light, dark },
    fonts: source.fonts,
    spacing: source.spacing,
    radius: source.radius,
  };
}

const kebabCase = (value) => value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
const cssVariables = (scheme) => Object.entries(scheme).map(([key, value]) => `  --color-${kebabCase(key)}: ${value};`).join("\n");

export function renderDesignTokenOutputs(tokens) {
  const header = "// Generated by tooling/scripts/generate-tokens.mjs. Do not edit directly.\n";
  const aliases = {
    ...Object.fromEntries(Object.keys(tokens.schemes.light).map((key) => [kebabCase(key), `var(--color-${kebabCase(key)})`])),
    background: "var(--color-background)",
    foreground: "var(--color-on-background)",
    primary: "var(--color-primary)",
    danger: "var(--color-error)",
  };
  const darkAliases = legacyColorKeys.map((key) => {
    const schemeKey = key === "foreground" ? "onBackground" : key === "danger" ? "error" : key;
    return `  --color-${key}: ${tokens.schemes.dark[schemeKey]};`;
  }).join("\n");
  const lightAliases = legacyColorKeys.map((key) => {
    const schemeKey = key === "foreground" ? "onBackground" : key === "danger" ? "error" : key;
    return `  --color-${key}: ${tokens.schemes.light[schemeKey]};`;
  }).join("\n");
  const typography = [
    ...Object.entries(tokens.fonts).map(([key, value]) => `  --font-${key}: ${value};`),
    ...Object.entries(tokens.spacing).map(([key, value]) => `  --spacing-${key}: ${value}px;`),
    ...Object.entries(tokens.radius).map(([key, value]) => `  --radius-${key}: ${value}px;`),
  ].join("\n");
  const darkBlock = `${cssVariables(tokens.schemes.dark)}\n${darkAliases}`;
  const css = `/* Generated by tooling/scripts/generate-tokens.mjs. Do not edit directly. */\n:root {\n${cssVariables(tokens.schemes.light)}\n${lightAliases}\n${typography}\n}\n:root[data-theme="dark"], .dark {\n${darkBlock}\n}\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${darkBlock.split("\n").map((line) => `  ${line}`).join("\n")}\n  }\n}\n`;
  return {
    typescript: `${header}export const theme = ${JSON.stringify(tokens, null, 2)} as const;\nexport type Theme = typeof theme;\n`,
    tailwind: `${header}module.exports = ${JSON.stringify({ colors: aliases, fontFamily: Object.fromEntries(Object.entries(tokens.fonts).map(([key, value]) => [key, [value]])), spacing: tokens.spacing, borderRadius: tokens.radius }, null, 2)};\n`,
    css,
  };
}
